// Generated by CoffeeScript 1.7.1

/*
 * utils/crypto_util 的测试类
 */

(function() {
  var accessKeyId, accessKeySecret, baseUri, debug, gamaSign, httpMethod, ignoreParams, params, should;

  should = require('should');

  debug = require('debug')('gama-search::tests::crypto_util_test');

  gamaSign = require('../index');

  accessKeyId = 'testid';

  accessKeySecret = 'testsecret';

  httpMethod = 'GET';

  baseUri = 'http://localhost:8086';

  params = {
    id: 'afdafaf',
    name: '哈哈',
    icons: 4234234,
    props: {
      242342: 1,
      434535: 2,
      345435: 3
    },
    text: "asfdadlfalksdjfkjsafkhashdfkldasklfjakjsdkfjkadsfkhkdashfkhkaldsjkfjdklsjf"
  };

  ignoreParams = ['icons', 'props'];

  describe("crypto_util test", function() {
    before(function() {});
    return describe("tests", function() {
      it('verifyTimestamp test', function(done) {
        console.log(gamaSign.verifyTimestamp(new Date().getTime() - 10000000));
        return done();
      });
      it('verifyMethod test', function(done) {
        var method, verify, _i, _len, _ref;
        _ref = ['GET', 'PPST', 'POST', 'put', 'delete'];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          method = _ref[_i];
          verify = gamaSign.verifyMethod(method);
          console.log("method:" + method + " verify:" + verify);
        }
        return done();
      });
      it('removeIgnoreParams test', function(done) {
        var newParams;
        newParams = gamaSign.removeIgnoreParams(params, ['icons', 'props']);
        console.dir(newParams);
        console.dir(params);
        return done();
      });
      return it('makeSign test', function(done) {
        var sign;
        sign = gamaSign.makeSign(httpMethod, baseUri, params, ignoreParams, accessKeyId, accessKeySecret);
        console.log(sign);
        params['sign'] = sign;
        sign = gamaSign.makeSign(httpMethod, baseUri, params, ignoreParams, accessKeyId, accessKeySecret);
        console.log(sign);
        return done();
      });
    });
  });

}).call(this);
