// Generated by CoffeeScript 1.7.1

/*
 * utils/crypto_util 的测试类
 */

(function() {
  var accessKeyId, accessKeySecret, debug, gamaSign, should;

  should = require('should');

  debug = require('debug')('gama-search::tests::crypto_util_test');

  gamaSign = require('../index');

  accessKeyId = 'testid';

  accessKeySecret = 'testsecret';

  describe("crypto_util test", function() {
    before(function() {});
    return describe("tests", function() {
      return it('verifyTimestamp test', function(done) {
        console.log(gamaSign.verifyTimestamp(new Date().getTime() - 10000000));
        return done();
      });
    });
  });

}).call(this);
